### ISSUE TITLE
COVAREP_feature_formant_extraction.m - wrong ref to perfile analysis

### ISSUE THREAD

**Issue by fusaroli** [covarep/covarep#104]
I've been testing the COVAREP_feature_formant_extraction.m and I found a couple of small issues
- the file calls itself on lines 65 and 77, while (I guess) it should be calling COVAREP_feature_formant_extraction_perfile
- calculating vowelspace on short sequences (e.g. with the default option of 0.01 s) is meaningless.

**Comment by fusaroli** [comment]
Actually I had to go and change the function name also in COVAREP_feature_formant_extraction_perfile.m, as the function name was COVAREP_feature_formant_extraction. Without changing the name in both files, the function kept telling me there were no wavs in my folder.

**Comment by gillesdegottex** [comment]
(I've huge problem to run Matlab again on my machine, so I cannot debug this directly sorry)

First message:
* The files in the repository already call COVAREP_feature_formant_extraction_perfile. Are you using the repository version?

*  0.01s seems to be the sampling rate of the features, not the window length. Am I missing something here?

2nd message: That's true, I've just corrected this.

**Comment by fusaroli** [comment]
I just downloaded the latest master and it's all in place now, thanks!
vowel-space: I see now it uses a special sampling. I still get 0s all over the place, but I'll do more testing and open a new issue in case I can't get it to work
